# Generated by Django 5.0.3 on 2024-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_timeslot_hour_alter_disponibilite_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_exam', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=10)),
                ('hour', models.CharField(max_length=25, null=True)),
                ('salle', models.CharField(max_length=10, null=True)),
                ('filiere', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RenameField(
            model_name='disponibilite',
            old_name='period',
            new_name='hour',
        ),
    ]
